### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by MatthijsKamstra**
More info about how to generate externs

### CODE REVIEW

**Comment by andyli** [comment]
1. I don't think we need pandas.
2. I think `haxelib install build.hxml` would be better since we wouldn't need to update the instruction if we changed the dependencies.

**Comment by MatthijsKamstra** [comment]
I uninstalled `pandas` (`pip3 uninstall pandas`) and got this error

```
→ python3 Main.py flask out
Traceback (most recent call last):
  File "Main.py", line 9427, in <module>
    pyextern_Process_pandas.classes = _hx_init_pyextern_Process_pandas_classes()
  File "Main.py", line 9426, in _hx_init_pyextern_Process_pandas_classes
    return _hx_local_0()
  File "Main.py", line 9417, in _hx_local_0
    module = importlib_Importlib_Module.import_module("pandas")
  File "/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 956, in _find_and_load_unlocked
ImportError: No module named 'pandas'
```

**Comment by MatthijsKamstra** [comment]
Indeed.... perhaps a little extra line

```
+ 4. `haxe build.hxml` 
       (if necessary follow haxelib instructions)
```

**Comment by MatthijsKamstra** [comment]
I did not know this: `haxe install build.hxml`
so much to learn, so little time
thx!

**Pull request closed without merging**
